In [1]:
import numpy as np
import pandas as pd
import sklearn

In [3]:
from sklearn.datasets import load_boston
df = load_boston()

In [4]:
df.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [7]:
print(df.data)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]

In [9]:
boston = pd.DataFrame(df.data, columns=df.feature_names)
boston.head(50)

       CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0   0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1   0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2   0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3   0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4   0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33
5   0.02985   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.12   5.21
6   0.08829  12.5   7.87   0.0  0.524  ...  5.0  311.0     15.2  395.60  12.43
7   0.14455  12.5   7.87   0.0  0.524  ...  5.0  311.0     15.2  396.90  19.15
8   0.21124  12.5   7.87   0.0  0.524  ...  5.0  311.0     15.2  386.63  29.93
9   0.17004  12.5   7.87   0.0  0.524  ...  5.0  311.0     15.2  386.71  17.10
10  0.22489  12.5   7.87   0.0  0.524  ...  5.0  311.0     15.2  392.52  20.45
11  0.11747  12.5   7.87   0.0  0.524  ...  5.0  311.0     15.2  396.90  13.27
12  0.09378  12.5   7.87   0.0  0.524  ...  5.0  311.0     15.2  390.50  15.71
13  0.62976   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  396.90   8.26
14  0.63796   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  380.02  10.26
15  0.62739   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  395.62   8.47
16  1.05393   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  386.85   6.58
17  0.78420   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  386.75  14.67
18  0.80271   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  288.99  11.69
19  0.72580   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  390.95  11.28
20  1.25179   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  376.57  21.02
21  0.85204   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  392.53  13.83
22  1.23247   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  396.90  18.72
23  0.98843   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  394.54  19.88
24  0.75026   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  394.33  16.30
25  0.84054   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  303.42  16.51
26  0.67191   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  376.88  14.81
27  0.95577   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  306.38  17.28
28  0.77299   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  387.94  12.80
29  1.00245   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  380.23  11.98
30  1.13081   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  360.17  22.60
31  1.35472   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  376.73  13.04
32  1.38799   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  232.60  27.71
33  1.15172   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  358.77  18.35
34  1.61282   0.0   8.14   0.0  0.538  ...  4.0  307.0     21.0  248.31  20.34
35  0.06417   0.0   5.96   0.0  0.499  ...  5.0  279.0     19.2  396.90   9.68
36  0.09744   0.0   5.96   0.0  0.499  ...  5.0  279.0     19.2  377.56  11.41
37  0.08014   0.0   5.96   0.0  0.499  ...  5.0  279.0     19.2  396.90   8.77
38  0.17505   0.0   5.96   0.0  0.499  ...  5.0  279.0     19.2  393.43  10.13
39  0.02763  75.0   2.95   0.0  0.428  ...  3.0  252.0     18.3  395.63   4.32
40  0.03359  75.0   2.95   0.0  0.428  ...  3.0  252.0     18.3  395.62   1.98
41  0.12744   0.0   6.91   0.0  0.448  ...  3.0  233.0     17.9  385.41   4.84
42  0.14150   0.0   6.91   0.0  0.448  ...  3.0  233.0     17.9  383.37   5.81
43  0.15936   0.0   6.91   0.0  0.448  ...  3.0  233.0     17.9  394.46   7.44
44  0.12269   0.0   6.91   0.0  0.448  ...  3.0  233.0     17.9  389.39   9.55
45  0.17142   0.0   6.91   0.0  0.448  ...  3.0  233.0     17.9  396.90  10.21
46  0.18836   0.0   6.91   0.0  0.448  ...  3.0  233.0     17.9  396.90  14.15
47  0.22927   0.0   6.91   0.0  0.448  ...  3.0  233.0     17.9  392.74  18.80
48  0.25387   0.0   6.91   0.0  0.448  ...  3.0  233.0     17.9  396.90  30.81
49  0.21977   0.0   6.91   0.0  0.448  ...  3.0  233.0     17.9  396.90  16.20

[50 rows x 13 columns]

In [11]:
boston['TARGET'] = df.target
boston.head()

      CRIM    ZN  INDUS  CHAS    NOX  ...  PTRATIO       B  LSTAT  MEDV  TARGET
0  0.00632  18.0   2.31   0.0  0.538  ...     15.3  396.90   4.98  24.0    24.0
1  0.02731   0.0   7.07   0.0  0.469  ...     17.8  396.90   9.14  21.6    21.6
2  0.02729   0.0   7.07   0.0  0.469  ...     17.8  392.83   4.03  34.7    34.7
3  0.03237   0.0   2.18   0.0  0.458  ...     18.7  394.63   2.94  33.4    33.4
4  0.06905   0.0   2.18   0.0  0.458  ...     18.7  396.90   5.33  36.2    36.2

[5 rows x 15 columns]

In [12]:
boston.isnull()

      CRIM     ZN  INDUS   CHAS    NOX  ...  PTRATIO      B  LSTAT   MEDV  TARGET
0    False  False  False  False  False  ...    False  False  False  False   False
1    False  False  False  False  False  ...    False  False  False  False   False
2    False  False  False  False  False  ...    False  False  False  False   False
3    False  False  False  False  False  ...    False  False  False  False   False
4    False  False  False  False  False  ...    False  False  False  False   False
..     ...    ...    ...    ...    ...  ...      ...    ...    ...    ...     ...
501  False  False  False  False  False  ...    False  False  False  False   False
502  False  False  False  False  False  ...    False  False  False  False   False
503  False  False  False  False  False  ...    False  False  False  False   False
504  False  False  False  False  False  ...    False  False  False  False   False
505  False  False  False  False  False  ...    False  False  False  False   False

[506 rows x 15 columns]

In [13]:
boston.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
TARGET     0
dtype: int64

In [14]:
from sklearn.model_selection import train_test_split
X = boston.drop('MEDV', axis=1)
Y = boston['MEDV']

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.15, random_state=5)
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(430, 14)
(76, 14)
(430,)
(76,)

In [17]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [18]:
lin_model = LinearRegression()  
lin_model.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
_train_predict = lin_model.predict(X_train)
rmse = (np.sqrt(mean_squared_error(Y_train, Y_train_predict)))


print("The model performance for training set")
print('RMSE is {}'.format(rmse))
print("\n")


# on testing set
y_test_predict = lin_model.predict(X_test)
rmse = (np.sqrt(mean_squared_error(Y_test, y_test_predict)))

print("The model performance for testing set")
print('RMSE is {}'.format(rmse))

In [22]:

print("The model performance for training set")
print('RMSE is {}'.format(rmse))
print("\n")


# on testing set
y_test_predict = lin_model.predict(X_test)
rmse = (np.sqrt(mean_squared_error(Y_test, y_test_predict)))


print("The model performance for testing set")
print('RMSE is {}'.format(rmse))

The model performance for training set
RMSE is 2.3355439547626242e-14


The model performance for testing set
RMSE is 2.3355439547626242e-14